### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maximuml** [sdvcrx/pan-baidu-download#51]
Please input this sharing password
jjbb
Traceback (most recent call last):
  File "bddown_cli.py", line 53, in <module>
    execute_command()
  File "bddown_cli.py", line 49, in execute_command
    commands[command](args[1:])
  File "/pan-baidu-download/command/download.py", line 111, in download
    if not hasExtension(fi.filename, extension):
  File "/pan-baidu-download/command/download.py", line 69, in hasExtension
    return file_ext.lower()[1:] == extension.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

please help!!!!!!

**Comment by sdvcrx** [comment]
Fixed, please pull code and try again ^_^
