### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mengmo** [sdvcrx/pan-baidu-download#55]
```
pan download https://pan.baidu.com/s/1jRv99Zx1FjV3OKC-JlZEzg
Please input this sharing password
1y8t
Traceback (most recent call last):
  File "D:\PortableApps\pan-baidu-download\bddown_cli.py", line 53, in <module>
    execute_command()
  File "D:\PortableApps\pan-baidu-download\bddown_cli.py", line 49, in execute_command
    commands[command](args[1:])
  File "D:\PortableApps\pan-baidu-download\command\download.py", line 102, in download
    fis = pan.get_file_infos(url, secret)
  File "D:\PortableApps\pan-baidu-download\bddown_core.py", line 228, in get_file_infos
    return [self.get_file_info(shareinfo, fsid=f['fs_id'], secret=secret) for f in self.all_files]
  File "D:\PortableApps\pan-baidu-download\bddown_core.py", line 182, in get_file_info
    fi.filename = _json['list'][0]['server_filename']
IndexError: list index out of range
```

**Comment by pz325** [comment]
It seems 'http://pan.baidu.com/api/sharedownload' responses list:[]. Maybe due to to a change of baidu pan's API?

**Comment by sdvcrx** [comment]
Sorry for the delay.

Please **login first** before downloading , now download api requires login token.

https://github.com/sdvcrx/pan-baidu-download#quick-start
